import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import Providers from "./providers";
import Whatsapp from "@/components/Home/Whatsapp";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="w-full max-w-[1440px] mx-auto ">
            <Header />
            <main className=" w-full">{children}</main>
          </div>
          <Whatsapp />
        </Providers>
      </body>
    </html>
  );
}
